name: ReturnNames
description: 'Take info from repo and make useable names from it.'
inputs:
  RepoName: 
    description: 'Name of the Repo'
    required: true
  SolutionName: 
    description: 'Name of the Solution'
    required: true
  PathToPackage: 
    description: 'Path to the nupkg'
    required: true
  Owner: 
    description: 'Owner of the Repo. Both user and org are valid.'
    required: true
  BuildSolutionType:
    desciption: 'Build Configuration switch.'
    required: true
    default: 'Release'
  
#outputs:
#  RepoName: 
#    description: 'Name of the Repo'
#    value: "${{ steps.RepoName.outputs._1 }}"

runs:
  using: "composite"

  steps:
  - uses: actions/checkout@v3
  
  - name: Setup NuGet
    uses: NuGet/setup-nuget@v1.0.5

  - name: Restore dependencies
    run: nuget restore ${{ inputs.SolutionName }}
    shell: bash
    
  - name: Setup .NET
    uses: actions/setup-dotnet@v2
    with:
      dotnet-version: 5.0.x

  - name: Add Github Source
    run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ inputs.Owner }}/index.json"
    shell: bash
    
  - name: Build
    run: dotnet build ${{ inputs.SolutionName }} --configuration ${{ inputs.BuildSolutionType }} --no-restore
    shell: bash

  - name: Pack
    id: PackForNuget
    run: dotnet pack --configuration ${{ inputs.BuildSolutionType }} 
    shell: bash

  - name: Put To Nuget
    run: dotnet nuget push "${{ inputs.PathToPackage }}" --api-key $NUGETTOKEN --source "github"
    shell: bash
